version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service

  user-service:
    build:
      context: ./backend/user-service
    ports:
      - "5000:5000"

  product-service:
    build:
      context: ./backend/product-service
    ports:
      - "5001:5001"

  order-service:
    build:
      context: ./backend/order-service
    ports:
      - "5002:5002"

  payment-service:
    build:
      context: ./backend/payment-service
    ports:
      - "5003:5003"

